dependents/node-filing-cabinet

.travis.yml, package.json, test/test.js
Not sure if it's a really good test, but it fails (along with the test above it, worryingly...) if #5 is reverted using node 4.3.1 (current LTS release)
=> Add test for #5

package.json
Wasn't getting the newer version of module-definition on an npm install in an existing project
=> Explicitly declare version of dep

index.js, test/test.js
We're not using loaders defined within the webpack config
because we don't care about the "compiled" output from the loader.
We only care about getting a partial path to map to a filepath.
=> Webpack: strip loader (if any) from the partial

index.js, package.json, test/test.js
Also produces a minor perf bump by avoiding the (relatively cheap) `resolveDependencyPath` logic and the (more expensive) filesystem check to see if the `resolveDependencyPath` result was a real file. In a hot code path, the savings is a few hundred ms.
=> Use CJS for ES6 module resolution

index.js, test/root1/mod1.js, test/root2/mod2.js, test/test.js, webpack-root.config.js
This will add support for resolving paths using the [resolve.root](http://webpack.github.io/docs/configuration.html#resolve-root) option. This was needed by a project I was running madge on that was setup [like this example](http://moduscreate.com/es6-es2015-import-no-relative-path-webpack/). The default for [enhanced-resolve](https://github.com/webpack/enhanced-resolve) is to resolve from `node_modules` so this PR will make paths in `resolve.root` overwriting that.
=> Support webpack resolve.root and resolve.modulesDirectories

index.js, test/test.js, webpack-root.config.js
Sorry for spamming you with PR's ;) But I realised that `resolve.modules` is actually supported by [webpack2](https://webpack.js.org/configuration/resolve/#resolve-modules) so we need to handle that. I also took the opportunity to fix the things you mentioned in the last PR. So it will no longer overwrite the config if `resolve.modules` is used and it will not add `node_modules` automatically.
=> Handle resolve.modules supported by webpack2

index.js, test/test.js, webpack-env.config.js
Long time no see! :) 
This adds support for webpack config intended to be used with the `--env` option. See https://webpack.js.org/configuration/configuration-types/#exporting-a-function-to-use-env
=> Support webpack config that exports a function

.travis.yml, index.js, package.json, test/test.js
so we wont load requirejs upfront, requirejs messes around with the node.vm and jest fails hard
=> make js dependency resolution lazy-loadable

package-lock.json, package.json
Little prep work for the other updates bubbling up.
Turns out babel wasn't really used so it can be dropped safely.
=> Drop the dev dependency on babel

package-lock.json, package.json
This will help dependency-tree to only depend on one version of typescript
=> Update typescript@3 for deduplication with detective-typescript

index.js, package-lock.json, package.json, readme.md
Doesn't break anything at the public api layer. This is all internal refactoring to allow for easier extension of arguments to certain resolvers.
Refactoring to support tsconfig to fix #34 and other downstream issues like https://github.com/pahen/madge/issues/184.
=> Move to an object form for resolvers

index.js, test/mockedJSFiles.js, test/test.js
This make sure imports like `./foo.svg` within ts/tsx files are reported
correctly.
Fixes #76.
=> Report non-typescript imports within typescript files

package-lock.json, package.json
This fixes an issue where dependency's would not be resolved on Windows.
See https://github.com/browserify/resolve/pull/156#issuecomment-496543642
=> Correctly resolve paths on Windows by updating resolve dependency

.gitignore, index.js, test/mockedJSFiles.js, test/test.js
Re: https://github.com/dependents/node-filing-cabinet/issues/85
=> Issue in tsConfig options resolving

index.js, test/mockedJSFiles.js, test/test.js
fix: https://github.com/dependents/node-filing-cabinet/issues/89
We have both TS and JS in the same project with `allowJs` typescript's `compillerOption`. `node-filing-cabinet` only looks up `.js` or `.jsx` on JS file but we expect to look up JS, `.ts` or `.tsx`.
This PR will make it solved.
=> Allow multiple default lookups for projects with JS and TS

.npmignore, .travis.yml, package-lock.json, package.json
Node.js 10 is a necessary prequisite to upgrade `enhanced-resolve` and (hopefully) `node-module-lookup-amd` after dependents/node-module-lookup-amd#29 is merged.
=> Require Node.js 10.13 and upgrade most dependencies

index.js, readme.md, test/test.js, webpack-multiple.config.js
support when webpack config is exported [multiple configurations](https://webpack.js.org/configuration/configuration-types/#exporting-multiple-configurations).
it might be nice to select a configuration which one to use, but this PR does not add this option, it always uses the first one.
=> support webpack multiple configurations

index.js, package-lock.json, package.json, readme.md, test/root3/README.md, test/root3/packages/bar/index.ts, test/root3/packages/foo/hello.ts, test/root3/packages/foo/index.ts, test/root3/tsconfig.json, test/test.js
Hi!
`ts.resolveModuleName` does not handle [Path Mapping](https://www.typescriptlang.org/docs/handbook/module-resolution.html#path-mapping). 
https://github.com/dependents/node-filing-cabinet/blob/754d3889e8ba53283a126eb69f08c71b760c8c2b/index.js#L227
Therefore, currently, Path Mapping is just ignored by `filing-cabinet`.
Fortunately, there is a library [tsconfig-path](https://github.com/dividab/tsconfig-paths#creatematchpath), thus I used it.
Path Mapping cannot be resolved without knowing an absolute path to tsconfig file (Accurately speaking, an absolute path to [`baseUrl`](https://www.typescriptlang.org/docs/handbook/module-resolution.html#base-url), which is calculated from an absolute path to tsconfig file). (And this is not `tsconfig-path`'s specific requirement. This is required …
=> feat(tsLookup): path mapping

index.js, test/test.js, test/ts/webpack.config.js
I'm using `node-dependency-tree` in typescript using webpack.
But, the `.ts` extension file cannot resolve the file specified in `resolve` in webpack config, because don't refer to webpack config.
So, I thought if webpack config is specified, how about changing it to use `resolveWebpackPath`?
But, There is a concern that this fix will result in breaking changes.
=> Support webpack config with TypeScript

index.js, test/test.js
**Reason:**
If ```.d.ts``` exists, ```ts``` resolve import as the path to the type-definition file by default (instead of the js file).
But if we set the ```noTypeDefinitions``` flag to true, 
we pass the unresolved import path to the ```ts.resolveJSModule```.
And if we have a type alias:
```
// tsconfig.json
{
"compilerOptions": {
"paths": {
"@test/*": ["*"]
}
}
}
```
our unresolved import looks like
```
@test/foo
```
instead of
```
<path_to_directory>/foo
```
Therefore ```ts``` cannot resolve this import and fails with an error.
**Solution:**
Pass to the ```ts.resolveJSModule``` resolved path of the import without extension.
Relates to: https://github.com/dependents/node-filing-cabinet/issues/112
=> Fix resolving js imports that have same-named ".d.ts" from ts with 'noTypeDefinitions' set to true

index.js, test/fixtures/webpack/webpack-root-string.config.js, test/fixtures/webpack/webpack-root.config.js, test/fixtures/webpack/webpack-roots.config.js, test/test.js
1. `resolve.root` maybe a string, used in webpack 1.x.
more detail here: https://github.com/webpack/webpack/issues/472#issuecomment-166946925
2. `resolve.roots` is used in latest webpack.
webpack docs: https://webpack.js.org/configuration/resolve/#resolveroots
=> fix: webpack roots

.github/workflows/ci.yml, .github/workflows/codeql.yml, .github/workflows/lint.yml, .npmrc, bin/cli.js, index.js, package-lock.json, package.json
=> Update dependencies and drop Node.js < 18 support

index.js, test/test.js
This primarily happens with my vite projects that import a virtual module.
The module in question is: virtual:pwa-register, which causes failedLookupLocations to be undefined and blows up on the filter call.
This prevents me from scanning my projects for circular dependencies.
Fixes #125
=> fix: handle `undefined` `failedLookupLocations`
